### ISSUE TITLE
Crash when entering a level, exiting,then leaving the level page

### ISSUE THREAD

**Issue by AhmedGhaith-0** [TheSillyDoggo/GeodeMenu#115]
2024-11-16T23:00:59.079730568 [I/ForceDarkHelperStubImpl]: initialize for com.geode.launcher , ForceDarkOrigin
2024-11-17T16:05:54.428812644 [I/ForceDarkHelperStubImpl]: initialize for com.geode.launcher , ForceDarkOrigin
2024-11-17T16:05:55.053934798 [W/Looper]: PerfMonitor doFrame : time=468ms vsyncFrame=0 latency=122ms procState=-1 historyMsgCount=5 (msgIndex=1 wall=128ms seq=2 late=5ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=108ms seq=3 late=131ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:05:55.064572875 [W/Looper]: PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=452ms procState=-1 historyMsgCount=5 (msgIndex=1 wall=468ms seq=7 late=122ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
2024-11-17T16:05:59.567020029 [W/Activity]: PerfMonitor: Slow Operation: Activity com.geode.launcher/.GeometryDashActivity onCreate took 2407ms
2024-11-17T16:05:59.644305260 [W/Looper]: PerfMonitor longMsg : seq=151 plan=16:05:57.136 late=7ms wall=2488ms running=0ms h=android.app.ActivityThread$H w=159 procState=-1
2024-11-17T16:05:59.644823029 [W/Looper]: PerfMonitor looperActivity : package=com.geode.launcher/.GeometryDashActivity time=0ms latency=2507ms running=0ms  procState=-1  historyMsgCount=4 (msgIndex=4 wall=2488ms seq=151 late=7ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:05:59.798032644 [W/Looper]: PerfMonitor doFrame : time=153ms vsyncFrame=0 latency=2488ms procState=-1 historyMsgCount=3 (msgIndex=1 wall=2488ms seq=151 late=7ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:06:49.187362109 [I/ForceDarkHelperStubImpl]: initialize for com.geode.launcher , ForceDarkOrigin
2024-11-17T16:06:49.651081494 [W/Looper]: PerfMonitor doFrame : time=317ms vsyncFrame=0 latency=118ms procState=-1 historyMsgCount=4 (msgIndex=1 wall=71ms seq=2 late=13ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=107ms seq=3 late=81ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:06:52.031466801 [W/Activity]: PerfMonitor: Slow Operation: Activity com.geode.launcher/.GeometryDashActivity onCreate took 538ms
2024-11-17T16:06:52.111794186 [W/Looper]: PerfMonitor looperActivity : package=com.geode.launcher/.GeometryDashActivity time=0ms latency=641ms running=0ms  procState=-1  historyMsgCount=3 (msgIndex=3 wall=637ms seq=172 late=4ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:06:52.238412648 [W/Looper]: PerfMonitor doFrame : time=126ms vsyncFrame=0 latency=635ms procState=-1 historyMsgCount=4 (msgIndex=1 wall=637ms seq=172 late=4ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:07:05.076719956 [I/ForceDarkHelperStubImpl]: initialize for com.geode.launcher , ForceDarkOrigin
2024-11-17T16:07:06.624786725 [W/Looper]: PerfMonitor looperActivity : package=com.geode.launcher/.GeometryDashActivity time=0ms latency=507ms running=0ms  procState=-1  historyMsgCount=4 (msgIndex=4 wall=499ms seq=66 late=8ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:07:06.666207725 [W/Looper]: PerfMonitor doFrame : time=41ms vsyncFrame=0 latency=493ms procState=-1 historyMsgCount=4 (msgIndex=1 wall=499ms seq=66 late=8ms h=android.app.ActivityThread$H w=159)
2024-11-17T16:09:08.011846194 [I/.geode.launche]: Using CollectorTypeCC GC.
2024-11-17T16:09:08.021831117 [E/.geode.launche]: Not starting debugger since process cannot load the jdwp agent.
2024-11-17T16:09:08.032848579 [I/MessageMonitor]: Load libmiui_runtime
2024-11-17T16:09:08.078411425 [I/.geode.launche]: Failed to open app image /data/app/~~2d2QMXTpHJFg2OGvHaiPsA==/com.geode.launcher-zQ_dAOM-R80bFmcDZC8aPA==/oat/arm64/base.art Invalid image header in '/data/app/~~2d2QMXTpHJFg2OGvHaiPsA==/com.geode.launcher-zQ_dAOM-R80bFmcDZC8aPA==/oat/arm64/base.art'
2024-11-17T16:09:08.092989809 [I/ForceDarkHelperStubImpl]: initialize for com.geode.launcher , ForceDarkOrigin
2024-11-17T16:09:08.094861194 [I/MiuiForceDarkConfig]: setConfig density:2.812500, mainRule:0, secondaryRule:0, tertiaryRule:0
2024-11-17T16:09:08.124109194 [E/QT]: [QT]file does not exist
2024-11-17T16:09:08.139586117 [W/System.err]: org.json.JSONException: No value for merlin
2024-11-17T16:09:08.139854117 [W/System.err]: at org.json.JSONObject.get(JSONObject.java:398)
2024-11-17T16:09:08.139881194 [W/System.err]: at org.json.JSONObject.getJSONObject(JSONObject.java:618)
2024-11-17T16:09:08.139899348 [W/System.err]: at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgsOfDevice(MiuiMultiWindowUtils.java:1433)
2024-11-17T16:09:08.139917271 [W/System.err]: at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgs(MiuiMultiWindowUtils.java:1427)
2024-11-17T16:09:08.139932348 [W/System.err]: at android.util.MiuiMultiWindowUtils.<clinit>(MiuiMultiWindowUtils.java:209)
2024-11-17T16:09:08.139951425 [W/System.err]: at com.android.internal.policy.DecorViewMultiWinStubImpl.<init>(DecorViewMultiWinStubImpl.java:19)
2024-11-17T16:09:08.139970502 [W/System.err]: at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideNewInstance(DecorViewMultiWinStubImpl$Provider.java:14)
2024-11-17T16:09:08.139987656 [W/System.err]: at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideNewInstance(DecorViewMultiWinStubImpl$Provider.java:8)
2024-11-17T16:09:08.140001502 [W/System.err]: at com.miui.base.MiuiStubRegistry.get(MiuiStubRegistry.java:129)
2024-11-17T16:09:08.140021271 [W/System.err]: at com.miui.base.MiuiStubUtil.newInstance(MiuiStubUtil.java:77)
2024-11-17T16:09:08.140034425 [W/System.err]: at com.android.internal.policy.DecorViewMultiWinStub.newInstance(DecorViewMultiWinStub.java:11)
2024-11-17T16:09:08.140047040 [W/System.err]: at com.android.internal.policy.DecorView.<init>(DecorView.java:335)
2024-11-17T16:09:08.140063040 [W/System.err]: at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2380)
2024-11-17T16:09:08.140075963 [W/System.err]: at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2760)
2024-11-17T16:09:08.140088348 [W/System.err]: at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2140)
2024-11-17T16:09:08.140100040 [W/System.err]: at b.m.a(SourceFile:22)
2024-11-17T16:09:08.140112886 [W/System.err]: at com.geode.launcher.MainActivity.onCreate(SourceFile:1)
2024-11-17T16:09:08.140125809 [W/System.err]: at android.app.Activity.performCreate(Activity.java:8163)
2024-11-17T16:09:08.140138502 [W/System.err]: at android.app.Activity.performCreate(Activity.java:8130)
2024-11-17T16:09:08.140153886 [W/System.err]: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
2024-11-17T16:09:08.140167348 [W/System.err]: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)
2024-11-17T16:09:08.140196656 [W/System.err]: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3947)
2024-11-17T16:09:08.140209194 [W/System.err]: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
2024-11-17T16:09:08.140221809 [W/System.err]: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2024-11-17T16:09:08.140237502 [W/System.err]: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2024-11-17T16:09:08.140252271 [W/System.err]: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
2024-11-17T16:09:08.140270117 [W/System.err]: at android.os.Handler.dispatchMessage(Handler.java:106)
2024-11-17T16:09:08.140282809 [W/System.err]: at android.os.Looper.loopOnce(Looper.java:210)
2024-11-17T16:09:08.140295348 [W/System.err]: at android.os.Looper.loop(Looper.java:299)
2024-11-17T16:09:08.140307656 [W/System.err]: at android.app.ActivityThread.main(ActivityThread.java:8280)
2024-11-17T16:09:08.140321271 [W/System.err]: at java.lang.reflect.Method.invoke(Native Method)
2024-11-17T16:09:08.140333886 [W/System.err]: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
2024-11-17T16:09:08.140348963 [W/System.err]: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
2024-11-17T16:09:08.174906502 [I/SurfaceFactory]: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@7cc2bbb
2024-11-17T16:09:08.176467040 [E/MsyncFactory]: [static] ClassNotFoundException
java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at java.lang.Class.forName(Class.java:512)
	at com.mediatek.view.MsyncFactory.<clinit>(MsyncFactory.java:14)
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:763)
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:859)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:393)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5012)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
	... 21 more

2024-11-17T16:09:08.176555733 [I/MsyncFactory]: [static] sMsyncFactory = com.mediatek.view.MsyncFactory@4cb6716
2024-11-17T16:09:08.278118809 [I/BufferQueueConsumer]: [](id:124200000000,api:0,p:-1,c:4674) connect: controlledByApp=false
2024-11-17T16:09:08.279577886 [I/BLASTBufferQueue]: [ViewRootImpl[MainActivity]#0] constructor()
2024-11-17T16:09:08.289162502 [E/OpenGLRenderer]: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
2024-11-17T16:09:08.289197194 [W/OpenGLRenderer]: Failed to initialize 101010-2 format, error = EGL_SUCCESS
2024-11-17T16:09:08.296675348 [I/BufferQueueProducer]: [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:124200000000,api:1,p:4674,c:4674) connect: api=1 producerControlledByApp=true
2024-11-17T16:09:08.302744886 [E/ion]: ioctl c0044901 failed with code -1: Invalid argument
2024-11-17T16:09:08.328119733 [E/OpenGLRenderer]: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
2024-11-17T16:09:08.328322117 [E/OpenGLRenderer]: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
2024-11-17T16:09:09.705687963 [W/RenderInspector]: QueueBuffer time out on com.geode.launcher/com.geode.launcher.MainActivity, count=1, avg=24 ms, max=24 ms.
2024-11-17T16:09:09.806292271 [W/RenderInspector]: DequeueBuffer time out on com.geode.launcher/com.geode.launcher.MainActivity, count=1, avg=23 ms, max=23 ms.
2024-11-17T16:09:09.939356656 [W/RenderInspector]: DequeueBuffer time out on com.geode.launcher/com.geode.launcher.MainActivity, count=1, avg=22 ms, max=22 ms.
2024-11-17T16:09:10.927759733 [W/MirrorManager]: this model don't Support
2024-11-17T16:09:10.983965810 [I/BufferQueueConsumer]: [](id:124200000001,api:0,p:-1,c:4674) connect: controlledByApp=false
2024-11-17T16:09:10.984573810 [I/BLASTBufferQueue]: [ViewRootImpl[MainActivity]#1] constructor()
2024-11-17T16:09:10.985879040 [I/BufferQueueProducer]: [ViewRootImpl[MainActivity]#1(BLAST Consumer)1](id:124200000001,api:1,p:4674,c:4674) connect: api=1 producerControlledByApp=true
2024-11-17T16:09:14.163193194 [I/BufferQueueConsumer]: [](id:124200000002,api:0,p:-1,c:4674) connect: controlledByApp=false
2024-11-17T16:09:14.163628348 [I/BLASTBufferQueue]: [ViewRootImpl[ApplicationLogsActivity]#2] constructor()
2024-11-17T16:09:14.164385887 [I/BufferQueueProducer]: [ViewRootImpl[ApplicationLogsActivity]#2(BLAST Consumer)2](id:124200000002,api:1,p:4674,c:4674) connect: api=1 producerControlledByApp=true

**Comment by Lilicogamer13** [comment]
i fixed it by uninstalling and installing again geode(and geometry dash)
